"""init

Revision ID: b73d20dd8e6e
Revises: 
Create Date: 2025-03-01 15:51:54.863913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b73d20dd8e6e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_instance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Имя агента"),
        sa.Column("type", sa.String(), nullable=False, comment="Тип агента"),
        sa.Column("instruction", sa.Text(), nullable=True, comment="Основная инструкция для агента"),
        sa.Column("response_format", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Формат ответа"),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Доступные инструменты и методы"),
        sa.Column("cloud_id", sa.String(), nullable=True, comment="ID агента в облачной систем"),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Конфигурация агента. Типичные настройки LLM"),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Дополнительные параметры агента"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Дата создания агента"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Дата обновления агента"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dialog",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False, comment="ID чата во внешней системе"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column("user_type", sa.String(), nullable=False, comment="Тип пользователя"),
        sa.Column("agent_id", sa.Integer(), nullable=False, comment="ID агента"),
        sa.Column("thread_id", sa.String(), nullable=True, comment="ID потока, если агент предусматривает такую логику"),
        sa.Column("started_at", sa.DateTime(), nullable=False, comment="Дата начала чата"),
        sa.Column("ended_at", sa.DateTime(), nullable=True, comment="Дата окончания чата"),
        sa.Column("last_message_at", sa.DateTime(), nullable=True, comment="Дата последнего сообщения"),
        sa.Column("price", sa.Numeric(), nullable=False, comment="Стоимость чата"),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Дополнительные параметры чата"),
        sa.ForeignKeyConstraint(["agent_id"], ["agent_instance.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_dialog_agent_id", "dialog", ["agent_id"], unique=False)
    op.create_index("ix_dialog_user", "dialog", ["user_id", "user_type"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dialog_id", sa.Integer(), nullable=False),
        sa.Column("sender", sa.String(length=50), nullable=False, comment="Тип отправителя сообщения. Пользователь, система или агент"),
        sa.Column("text", sa.Text(), nullable=True, comment="Текст сообщения"),
        sa.Column(
            "media",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='Медиа-файлы. Формат: [{"mimetype": "image/jpeg", "type": "img", "url": "https://upload.com/some_image", "extension": "jpg", "name": "img_name", "size": 123}]',
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="Дата создания сообщения"),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Дополнительные параметры сообщения"),
        sa.ForeignKeyConstraint(["dialog_id"], ["dialog.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_dialog_id"), "message", ["dialog_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_dialog_id"), table_name="message")
    op.drop_table("message")
    op.drop_index("ix_dialog_user", table_name="dialog")
    op.drop_index("ix_dialog_agent_id", table_name="dialog")
    op.drop_table("dialog")
    op.drop_table("agent_instance")
    # ### end Alembic commands ###
