"""инструкция для консолидации

Revision ID: bd440790dedc
Revises: ea9d95a9013f
Create Date: 2025-03-01 16:35:21.672111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd440790dedc'
down_revision: Union[str, None] = 'b73d20dd8e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_instance', sa.Column('consolidation_instruction', sa.Text(), nullable=True, comment='Инструкция для консолидации в VectorStore'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_instance', 'consolidation_instruction')
    # ### end Alembic commands ###
